### ISSUE TITLE
angular-watchers breaks angular lifecycle

### ISSUE THREAD

**Issue by Den-dp** [tiagojsalmeida/angular-watchers#2]
For some reason `angular-watchers` extension forces my angular services to initialize. That's of course a good test for the presence of a race conditions… But unfortunally I have some in my app and right now I'm suffering a bit.

Here is the code
http://plnkr.co/edit/u4YJzqVqE1gw9SOTv1t4

And here is live example to play with (no iframes)
http://run.plnkr.co/plunks/u4YJzqVqE1gw9SOTv1t4/

Output with this extension:

```
FeatureOneService instantiated!
FeatureTwoService instantiated!
```

Output without this extension:

```
FeatureOneService instantiated!
```

Is it possible to get rid of this strange behaviour?
Thanks!

**Comment by tiagojsalmeida** [comment]
Hi @Den-dp .

This is because the extension enables you to access to all the services/modules from the console (with window.$$am) which means we are injecting them (and therefore they initialise).

I will create a new version disabling this feature by default and adding a config page.
Would that work for you?

Thanks,
Tiago Almeida

**Comment by Den-dp** [comment]
Oh, now I see.

So yes, it would be awesome to have this feature as option but disabled by default.

Thanks for quick response and for this extension!

**Comment by Den-dp** [comment]
Looks like fixed by https://github.com/tiagojsalmeida/angular-watchers/commit/2f0d19e7b65c7ca4ece976e36d30fe739bd0932b

**Comment by tiagojsalmeida** [comment]
@Den-dp sorry for the delay.
